### ISSUE TITLE
properties reload fails on version 1.18.2

### ISSUE THREAD

**Issue by mezzoEmrys** [chylex/Minecraft-Server-Properties-Reload#1]
Release 1.0.3 states that it supports 1.18+, and does support 1.18.1, but on 1.18.2 the following error occurs:

```
[23:09:00] [Server thread/INFO]: Reloading server properties:
[23:09:00] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.class_5455 net.minecraft.class_3176.method_30611()'
        at chylex.serverproperties.command.PropertiesCommand.reloadPropertiesFile(PropertiesCommand.java:57) ~[ServerPropertiesReload-Fabric-1.18+v1.0.3.jar:?]
        at chylex.serverproperties.command.PropertiesCommand.lambda$register$1(PropertiesCommand.java:32) ~[ServerPropertiesReload-Fabric-1.18+v1.0.3.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java:264) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_13941(class_3176.java:338) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:323) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

A new release will likely need to target 1.18.2, or compatibility would need to be added to select methods based on version.

**Comment by chylex** [comment]
Released a fixed version for 1.18.2. There are no actual changes, but binary compatibility broke between 1.18.1 and 1.18.2.
